project_path: .
ddconfig_path: configs/ddconfigs/whale_sequence.json
model_path: models/sequifier-no-pulse3-best-200.onnx
data_path: data/whale_sequence-split2.csv
read_format: csv

selected_columns: ["interval", "speaker", "word_switch"] # should include all target column, can include additional columns
target_columns: ["interval", "speaker",  "word_switch"]
target_column_types: # 'criterion' in training_spec must also be adapted
  interval: real
  speaker: categorical
  word_switch: categorical

output_probabilities: false
map_to_id: true
device: mps
seq_length: 25
inference_batch_size: 10

autoregression: true
autoregression_additional_steps: 20