project_path: .
ddconfig_path: configs/ddconfigs/whale_sequence.json
model_path: PLEASE FILL
data_path: PLEASE FILL

selected_columns: ["interval", "speaker"] # should include all target column, can include additional columns
target_columns: ["interval", "speaker"]
target_column_types: # 'criterion' in training_spec must also be adapted
  interval: real
  speaker: categorical

output_probabilities: false
map_to_id: false
device: mps
seq_length: 25
inference_batch_size: 10

autoregression: true
autoregression_additional_steps: 20