project_path: .
data_path: data/whale_sequence.csv
read_format: csv
write_format: csv
selected_columns: ["interval", "pulse", "speaker"] # should include all target column, can include additional columns
target_columns: ["interval", "pulse", "speaker"]

seq_length: 25
seq_step_size: 1
group_proportions:
- 0.8
- 0.1
- 0.1
max_rows: 
n_cores: 1