project_path: .
model_name: no-pulse
read_format: csv
ddconfig_path: configs/ddconfigs/whale_sequence.json

selected_columns: ["interval", "speaker"] # should include all target column, can include additional columns
target_columns: ["interval", "speaker"]
target_column_types: # 'criterion' in training_spec must also be adapted
  interval: real
  speaker: categorical

seq_length: 25
inference_batch_size: 10

export_onnx: true

model_spec:
  d_model: 64
  nhead: 4
  d_hid: 64
  nlayers: 2
training_spec:
  device: mps
  epochs: 100
  iter_save: 5
  batch_size: 100
  log_interval: 10
  lr: 0.0008
  accumulation_steps: 1
  dropout: 0.2
  criterion:
    interval: MSELoss
    speaker: CrossEntropyLoss
  optimizer:
    name: AdamW
  scheduler:
    name: StepLR
    step_size: 1
    gamma: 0.98
  continue_training: true